# Generated by Django 4.1.3 on 2022-12-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_category_categorydb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorydb',
            new_name='categordb',
        ),
    ]
