# Generated by Django 4.1.3 on 2022-12-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='QUANTITY',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
